version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/fitx-fetcher:latest@sha256:2e9fd4114d244ff04dbdad936e0167ab67a6177f4421d0f8e16e57ec240c5866
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - FITX_EMAIL=${FITX_EMAIL}
      - FITX_PASSWORD=${FITX_PASSWORD}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
