version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/fitx-fetcher:latest@sha256:c71a8d074ea1ef34d443c4cfe3d72e76be61158d5148985519bfd098ee4a5040
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - FITX_EMAIL=${FITX_EMAIL}
      - FITX_PASSWORD=${FITX_PASSWORD}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
