version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/fitx-fetcher:latest@sha256:d992a95dd3876175ef9bbb5ebbea049c44cffebb48dff1329092a164ca8d837f
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - FITX_EMAIL=${FITX_EMAIL}
      - FITX_PASSWORD=${FITX_PASSWORD}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
